import Head from 'next/head';
import styled from 'styled-components';

const StyledTest = styled.div`
  color: ${({ theme }) => theme.colors.primary500};
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <StyledTest>esto es el index</StyledTest>
    </div>
  );
}
